development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  host: localhost
  username: pedatela
  password: "lucasspc"
  database: monolitico_db

production:
  adapter: postgresql
  database: monolitico_db
  pool: 5
  timeout: 5000
